site_name: Insightio
theme:
  name: material
  favicon: 'assets/favicon.ico'

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
        
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/CankayaUniversity/ceng-407-408-2023-2024-Insightio