rtsp_address: ""
line_start_x: 200
line_start_y: 140
line_end_x: 440
line_end_y: 340
road_line_1_start_x: 300
road_line_1_start_y: 0
road_line_1_end_x: 300
road_line_1_end_y: 720
road_line_2_start_x: 980
road_line_2_start_y: 0
road_line_2_end_x: 980
road_line_2_end_y: 720
road_line_thickness: 2
show_camera_window: True
mongo_url: "mongodb://localhost:27017/"
sayac: "sayac1"
api_post_url: ""
api_get_url: ""