server:
  port: 8090
  compression:
    enabled: true
  http2:
    enabled: true
  shutdown: graceful

springdoc:
  api-docs:
    path: /api-docs
spring:
  data:
    mongodb:
      uri: mongodb://localhost/user-insightio

